export default {
  login: "esjmb",
  id: 2598233,
  node_id: "MDQ6VXNlcjI1OTgyMzM=",
  avatar_url: "https://avatars.githubusercontent.com/u/2598233?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/esjmb",
  html_url: "https://github.com/esjmb",
  followers_url: "https://api.github.com/users/esjmb/followers",
  following_url: "https://api.github.com/users/esjmb/following{/other_user}",
  gists_url: "https://api.github.com/users/esjmb/gists{/gist_id}",
  starred_url: "https://api.github.com/users/esjmb/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/esjmb/subscriptions",
  organizations_url: "https://api.github.com/users/esjmb/orgs",
  repos_url: "https://api.github.com/users/esjmb/repos",
  events_url: "https://api.github.com/users/esjmb/events{/privacy}",
  received_events_url: "https://api.github.com/users/esjmb/received_events",
  type: "User",
  site_admin: false,
  name: "Stephen Barrett",
  company: "TCD",
  blog: "www.scss.tcd.ie",
  location: "Dublin",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 12,
  public_gists: 0,
  followers: 49,
  following: 1,
  created_at: "2012-10-19T10:34:43Z",
  updated_at: "2020-11-30T13:15:11Z"
  }