export default {
  login: "example user",
  id: null,
  node_id: null,
  avatar_url: null,
  gravatar_id: "",
  url: null,
  html_url: null,
  followers_url: null,
  following_url: null,
  gists_url: "",
  starred_url: "",
  subscriptions_url: "",
  organizations_url: "",
  repos_url: "",
  events_url: "",
  received_events_url: "",
  type: "User",
  site_admin: false,
  name: "example",
  company: "example",
  blog: "",
  location: "world",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: "example",
  public_repos: 1,
  public_gists: 1,
  followers: 1,
  following: 0,
  created_at: "2009-01-17T13:42:51Z",
  updated_at: "2021-01-29T13:46:51Z"
  }